"""fix peer endpoint uniqueness

Revision ID: a47004e8d45f
Revises: df56bd840837
Create Date: 2026-02-04 10:14:16.530701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47004e8d45f'
down_revision: Union[str, Sequence[str], None] = 'df56bd840837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('peers_endpoint_key'), 'peers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('peers_endpoint_key'), 'peers', ['endpoint'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
