"""add unique constraint and remove name field in peer model

Revision ID: e7b0fb25b8e9
Revises: a47004e8d45f
Create Date: 2026-02-04 12:26:29.055832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b0fb25b8e9'
down_revision: Union[str, Sequence[str], None] = 'a47004e8d45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peers_name'), table_name='peers')
    op.create_index(op.f('ix_peers_app_type'), 'peers', ['app_type'], unique=False)
    op.create_index(op.f('ix_peers_client_id'), 'peers', ['client_id'], unique=False)
    op.create_unique_constraint('uq_peers_client_app_type', 'peers', ['client_id', 'app_type'])
    op.drop_column('peers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('uq_peers_client_app_type', 'peers', type_='unique')
    op.drop_index(op.f('ix_peers_client_id'), table_name='peers')
    op.drop_index(op.f('ix_peers_app_type'), table_name='peers')
    op.create_index(op.f('ix_peers_name'), 'peers', ['name'], unique=True)
    # ### end Alembic commands ###
